repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: no-commit-to-branch

  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.1b3
    hooks:
      - id: hadolint
        name: lint Dockerfiles

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.5.0
    hooks:
      - id: eslint
        name: lint JS/TS and Vue files
        types:
          - vue
          - javascript
          - ts

  - repo: https://github.com/Weburz/crisp
    rev: v0.1.6
    hooks:
      - id: crisp
        stages: [commit-msg]
        name: lint git-commit messages

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.0
    hooks:
      - id: terraform_fmt
        name: format Terraform files
      - id: terraform_validate
        name: validate Terraform files
      - id: terraform_tflint
        name: lint Terraform files
      - id: terraform_checkov
        name: check for potential security issues in the IaC

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.0
    hooks:
      - id: terraform_fmt
        name: format Terraform files
      - id: terraform_validate
        name: validate Terraform files
      - id: terraform_tflint
        name: lint Terraform files
      - id: terraform_checkov
        name: check for potential security issues in the IaC
